### ISSUE TITLE
webman引入event_loop后连接数不会释放

### ISSUE THREAD

**Issue by 81549361** [cloudtay/ripple#32]
通过php webman status 查询的http 服务的connections会一直累加，直到重启服务或reload
通过php webman connections 命令查看，存在上万大量以下连接，并且一直增加。
```
443765   xxxx         77402     tcp     Http             1      0     0B           0B           1.4KB        107.9KB       ESTABLISHED    172.18.0.2:8787        172.69.135.34:27507
```

通过netstat -an | grep :8787 | wc -l命令查看连接数仅仅26个。

**Comment by cclilshy** [comment]
简单描述一下相关依赖的版本信息和控制器行为, 这是我这儿复现的结果, 希望对你有帮助

- workerman@4x
- ripple-driver@1.3
- webman-coroutine@1.1.4

![Xnip2024-10-14_11-13-55](https://github.com/user-attachments/assets/3c9e3d53-5740-42c3-914a-4fb3272f4ab9)

**Comment by 81549361** [comment]
> 简单描述一下相关依赖的版本信息和控制器行为, 这是我这儿复现的结果, 希望对你有帮助
> 
> * workerman@4x
> * ripple-driver@1.3
> * webman-coroutine@1.1.4
> 
> ![Xnip2024-10-14_11-13-55](https://private-user-images.githubusercontent.com/59851383/376099927-3c9e3d53-5740-42c3-914a-4fb3272f4ab9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzYxOTksIm5iZiI6MTcyODg3NTg5OSwicGF0aCI6Ii81OTg1MTM4My8zNzYwOTk5MjctM2M5ZTNkNTMtNTc0MC00MmMzLTkxNGEtNGZiMzI3MmY0YWI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAzMTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OWE4MGQ4MmRkNjM5MjFkYjJkNTM3M2E1YTQ0ODhiYWMwZmY3YjU3M2Y5YTM4NTM5Y2JiZmNiN2Q2MzllNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ESyPseF5lEFWWEYyt8chyXbhFkOatm9TvJZK402IJwY)

谢谢解答，应该是长连接导致的
